version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip wget git gcc clang python libc6 curl libstdc++6 git wget libssl-dev zstd
           git config --global user.name "ItsVixano"
           git config --global user.email "vixanonew@gmail.com"
           git config --global color.ui false
           git clone --depth=1 -b fox-oc --single-branch https://github.com/Fox-kernel/Fox_kernel_ysl-4.9 ysl
           cd ysl
           wget https://raw.githubusercontent.com/Fox-kernel/myscripts/master/ysl.sh
           source ysl.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
